### ISSUE TITLE
ERROR: BAM file index (.bai) does not exist 

### ISSUE THREAD

**Issue by ls233** [ncbi/BAMscale#15]
Hi there

I'm using BAMscale Version: v0.0.5 .
The "scale" utility is reporting "ERROR: BAM file index (.bai) does not exist". The manual check for index (.bai) however shows it does exist. I'm happy to share the BAM file and it's index (.bai) but I'm not sure what is the best way to do it here.

**Comment by pongorlorinc** [comment]
Hi Is233,

Probably the index name you have is not what BAMscale expects by default. BAMscale looks for index that have the complete bam file name, followed by the .bai suffix.

Eg. For a BAM names "alignment.bam", the index expected would be "alignment.bam.bai".
In this example, maybe you index is "alignment.bai"?

**Comment by pongorlorinc** [comment]
Hi  Is233,

I will close the discussion, let me know if there are any other questions that come up!

Best wishes,
Lorinc

**Comment by ls233** [comment]
Thanks. Indeed my index file followed the "alignment.bai" format. BAM indexing packages use different approaches and it'd be nice if the users of your package didn't have to create an additional set of index file just for running your tool.

**Comment by pongorlorinc** [comment]
Hi Is233,

I will check this out, and will let you know if I was able to update it. I think it is a good idea to add this possibility.

**Comment by pongorlorinc** [comment]
Hi Is233,

Added the possibility to support the "short" index name. Please give it a try in the new version, and let me know how it works! :)

We want to be sure that it runs correctly.

Thank you,
Lorinc
