### ISSUE TITLE
Rounding to more than two decimal places

### ISSUE THREAD

**Issue by jelber2** [ncbi/BAMscale#17]
Let's say you want to use BAMscale to calculate a library size scaling factor using a command such as the following (example command, not real data)

    $ BAMscale scale --operation rna --threads 20 \
    --bam 162260/162260.bam \
    --bam 162261/162261.bam > BAMscale.log 2>&1

    $ grep -P -A 2 "Sample: \d+.bam" BAMscale.log|paste - - - -

    Sample: 162260.bam	Total no. of reads: 537060		Library size scale: 0.00	--
    Sample: 162261.bam	Total no. of reads: 1883		Library size scale: 1.00	--

If there is huge difference in the number of reads between the largest and smallest library, the estimated Library size scale will be 0.00 due to rounding to only 2 decimal places. Is there some way to either expose an option to make this value user adjustable or just simply set it to maybe 8 decimal places?

**Comment by pongorlorinc** [comment]
Good question!

By default, bamscale doesnt round when normalizing. In the stdout, it
rounds to 2 decimals, to make the command line neater.

So in short, it uses the float length when scaling.
In cases like this, large differences can be problematic, although scaling
helps.

What I do in RNA-seq is use DESeq2 (or edgeR) to get the scaling factor,
get the reciprocal value for each sample ( 1/scalingfactor ), and use those
values in BAMscale. In this case, I would suggest running the command
separately for each bamfile.

BAMscale scale --bam <RNAseq1.bam> --scale custom --factor 1.24
BAMscale scale --bam <RNAseq2.bam> --scale custom --factor 0.76

But you currently have to specify the "--scale custom" too.

WE had pretty good success with DESeq2+BAMscale (in RNA mode), even in
cases where some samples were much smaller, but it won't be perfect.

Example here:
https://github.com/ncbi/BAMscale/wiki/Detailed-usage:-RNA-seq-coverage-tracks#scaling-to-a-custom-factor

 Hope this helps'

Best wishes,
Lorinc

**Comment by pongorlorinc** [comment]
PS, When specifying custom scaling factors, you can give longer floats
(this might be rounded on the stdout), but the full float is used.

**Comment by jelber2** [comment]
@pongorlorinc thank you very much for the insight and help!
