### ISSUE TITLE
statistic from tpm normalized peaks

### ISSUE THREAD

**Issue by lmanchon** [ncbi/BAMscale#18]
--Hi,

i want to emphasize the best peaks and i think to do that i need to compute some statistics using the tpm output.
But i'm not very familiar with stats and i don't known how to do. Do you have some clues or tuto ? Thank you .

best,
L.

**Comment by pongorlorinc** [comment]
Hi lmanchon,

There are a few options on what you could do. On one side, if it as experiment setup, where you have replicates for each condition, you could use differential expression analysis tools from the raw read counts table (such as DESeq2 or edgeR). 

If no replicates are available, you could try to look for sites based on higher ranges of signal across samples. In these cases what I do is look for sites with the highest standard deviation from either the normalized signal (TPM or FPKM). In a lot of cases, it may help to log2 transform your data before analysis (in case of log transformation, I usually add 1 to every value, since zero values can give an error).

Let me know if this helps!

Best wishes,
Lorinc

**Comment by lmanchon** [comment]
--Hi,
 
indeed, I have no replicates only a contral and experience. I think I will use the TPM and then transform them into log2 as you say but after which test to apply? T-test ?

for example this is an extract of my result:

- [ chr20:79360-114359      90.461288       93.571472
chr20:79360-83302       63.613495       105.795517
chr20:79360-83302       63.613495       105.795517
chr20:80652-461103      80.270264       87.637375
chr20:80652-96321       89.427116       91.615036
chr20:80653-158935      102.081039      87.090317
chr20:80664-212680      102.937920      85.527283
chr20:80895-217034      102.684700      85.355522
chr20:81037-127687      96.766785       93.633598
chr20:82603-120721      96.194977       94.207069
chr20:82603-127687      97.588951       93.477928
chr20:82603-144480      98.161407       88.115570
chr20:88627-88801       123.055962      100.918564
chr20:88767-232882      102.544601      85.749084
chr20:89024-98143       97.262856       100.132805
chr20:95107-296217      93.900497       85.524605
chr20:107044-111576     111.663322      88.147865
chr20:108569-297747     93.608887       84.723030
chr20:108569-297747     93.608887       84.723030
chr20:119864-144480     101.636307      78.825195
chr20:119864-158815     109.667061      79.794861
chr20:124875-190385     109.675964      82.089714
chr20:127143-184361     109.709267      80.789696
chr20:128359-135409     57.179733       54.173939
chr20:130059-133359     55.775330       50.551025
chr20:133101-204386     109.952026      82.521461
chr20:137141-144551     141.866928      91.235283
chr20:137830-261754     103.054016      83.920853
chr20:141142-201445     113.485580      84.082062
chr20:143661-201326     112.322037      84.046005
chr20:156390-157259     140.255692      116.189888
chr20:166738-201445     112.577576      89.678734
chr20:167152-173814     125.222794      101.479042
chr20:196684-201168     110.930222      88.112427
chr20:198106-201932     110.097946      88.349899
chr20:200997-256161     91.438454       84.195755
chr20:206512-250909     94.378273       84.443176
chr20:207466-247326     96.360664       82.270393
chr20:207466-247326     96.360664       82.270393
chr20:214303-216668     99.589470       85.386063
chr20:215918-216701     108.331314      50.459282
chr20:216521-434561     68.616035       88.205849
chr20:231935-248826     99.656143       84.207336
chr20:236170-247325     106.235535      77.921249] 


best,
Laurent --

**Comment by pongorlorinc** [comment]
Hi Laurent,

You could try using the difference between the two condition and group them by which peaks go up (positive) or down (negative), and get the ones with highest change (eg. top 1000 peaks with highest mean difference based on absolute value). Afterwards you could try to do enrichment analysis of genes (ChIPseeker worked well for me), and maybe motif analysis.

Best wishes,
Lorinc
