### ISSUE TITLE
strand-specific definition

### ISSUE THREAD

**Issue by mmpust** [ncbi/BAMscale#19]
Hi,

is ```endseq: strand-specific coverages``` in this context referring to the strand specificity based on the underlying DNA reference or based on sense/antisense RNA transcription for strand-specific RNA libraries?

Thanks!

**Comment by pongorlorinc** [comment]
Hi,

To my understanding the END-seq is sequenced in a strand specific manner, so the strand information can be retrieved by the alignment orientation, which is used by BAMscale.

Hope this helps!

Best wishes,
Lorinc

**Comment by mmpust** [comment]
Thanks for your quick reply! Can you explain this a bit more? 
Because my library is strand-specific. Thus, I have sense and antisense transcription in a bacterial cell. But both DNA strands in a bacterial genome (positive and negative strand) can act as template for sense and antisense transcription. So, is BAMscale referring to the positive/negative DNA strand/template or sense/antisense transcription of a gene?
Thanks!

**Comment by pongorlorinc** [comment]
Hi,

when you specify the stranded options, BAMscale follows the strand of the mapped read, as in the flag that specifies if the read maps to the positive or negative strand of the sequence.

Best wishes,
Lorinc
