### ISSUE TITLE
Replication timing segmentation with ENCODE data?

### ISSUE THREAD

**Issue by pierrj** [ncbi/BAMscale#20]
Hello, I'd like to use your Replication_timing_segmenter.R to call replication timing segments using data available from Encode. If you aren't familiar with that data, each cell type comes with G1, G2, S1, S2, S3, and S4 samples. I was having a hard time finding which sample to use as the asynchronous S-phase for the purposes of calculating replication timing segments. Have you done something like this before? Do you have any advice on which samples to use? Thanks!

**Comment by pongorlorinc** [comment]
Hi Pierrj,

Unfortunately I have not tested it with encode data. As long as it is sequencing based, you could try different combinations of G-phase and S-phase samples, but not sure what would be the best approach. I would probably start by visualizing the different phases, see how different they are.

Although the segmenter script works somewhat well with some data, you may need to also play around with different settings and parameters.

Lorinc

**Comment by pongorlorinc** [comment]
Will close this discussion for now.
