### ISSUE TITLE
Hi, is it possible to get a compiled version?

### ISSUE THREAD

**Issue by biwdpang** [ncbi/BAMscale#21]
Hi, this is a good work.

But it's diffcult in linux not root to install, is it possibie to get a compiled version?

**Comment by pongorlorinc** [comment]
Hi biwdpang,

Thank you!

In theory you don't need root access to install the program, after compiling it, the executable should be in the "bin" folder within the BAMscale folder. 

Best wishes,
Lorinc

**Comment by biwdpang** [comment]
Thank for your reply.

I have a diffult in compliling, but now i use conda to finish this install.

**Comment by doliv071** [comment]
I also found installation from source rather tricky so I'll leave a comment here for anyone else who wants to avoid conda or docker installations. 

The first error I ran into is that htslib must be installed separate from samtools (samtools brings it's own htslib but for some reason it isn't accessibly system-wide). The second issue is using `make install` for libBigWig will place the headers in the system location which will cause problems with the `CPPFLAGS` and `LDFLAGS` that are set in the documentation. 

Here is how I built it on my system (including htslib, samtools, and libBigWig compiled from source)

```
# assuming you are installing in some user accessible directory 
cd ~/software

# htslib
wget https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2
tar -xjvf htslib-1.21.tar.bz2
rm htslib-1.21.tar.bz2
cd htslib-1.21
# curses is only needed for tview which we don't need/use
./configure
make -j && sudo make install
cd ~/software

#samtools
wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2
tar -xjvf samtools-1.21.tar.bz2
rm samtools-1.21.tar.bz2
cd samtools-1.21
./configure
make -j && sudo make install
cd ~/software

# libBigWig
git clone https://github.com/dpryan79/libBigWig.git
cd libBigWig
git checkout 0.4.7
make -j && sudo make install

# set these for BAMscale to use
export CPPFLAGS="-I /usr/local/include"
export LDFLAGS="-L /usr/local/lib -Wl,-rpath,/usr/local/lib"
cd ~/software

# now bamscale
git clone https://github.com/ncbi/BAMscale.git
cd BAMscale
git checkout v0.0.5
make -j
cd bin/ 
mv BAMscale /usr/local/bin/
cd ~/software
```

my system info:
```
Ubuntu 24.04 LTS
GCC 13.2.0
```
