### ISSUE TITLE
Synchronize github version to sofrware version

### ISSUE THREAD

**Issue by doliv071** [ncbi/BAMscale#23]
I'm wondering if you would consider synchronizing the github version to the software reported version. Right now the github release tag is `v0.0.5` while the software reports `v1.0`.

My main issue is automating validation that the pulled and installed versions match e.g.
```
BAMSCALE_VERSION="0.0.5"

git clone https://github.com/ncbi/BAMscale.git
cd BAMscale
git checkout v${BAMSCALE_VERSION}
make -j
mv bin/BAMscale ~/.local/bin/

BAMSCALE_INSTALLED=$(BAMscale 2>&1 | grep Version | sed -e "s/Version: //g")

if [ "$BAMSCALE_INSTALLED" == "v${BAMSCALE_VERSION}" ]; then 
  echo "pass"
else 
  echo "fail"
fi
```

**Comment by r78v10a07** [comment]
Hi, thanks for posting this.
I created a new tag v0.0.7 with the fix.
