### ISSUE TITLE
executable for MAC

### ISSUE THREAD

**Issue by obalasz** [ncbi/BAMscale#9]
Is there a static executable available for MAC OS? It would be a great help.

**Comment by r78v10a07** [comment]
Hi,
It is very complicated or almost impossible to create a static executable in Mac OS.
Check this link:
https://stackoverflow.com/questions/5259249/creating-static-mac-os-x-c-build
We will improve the README to make more clear the compiling process.
Thanks,
Roberto

**Comment by pongorlorinc** [comment]
Hi obalasz,

We created a detailed installation in the manual ( https://github.com/ncbi/BAMscale/wiki/Installation ).

You can either install with conda, or compile it (you might need to be su to install the libBigWig lib)

I hope it is helpful! Let me know if you have any questions.

Best,
Lorinc
